version: '3.8'

services:
  telegram-bot:
    build: .
    environment:
      - BOT_TOKEN=7644996926:AAFAqmY7nz8riytHLKfkUGKjp5t6RO96wGo
      - API_URL_TEMPLATE=https://godtufan-like.vercel.app//like?uid={uid}&server_name={region}&key=BHUPALI×GAGAN
      - WEBHOOK_URL=https://fearless-kanhaapi.onrender.com/
      - PORT=5000
    ports:
      - "5000:5000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M